import type { MediaFileRecord } from "./mediaScanner";

/*
 * The renderer should be able to say "show media item abc123", but it should
 * not be able to say "read this absolute path from disk". MediaRegistry maps
 * app-generated IDs back to real paths, so custom protocol handlers can serve
 * only files from the current scan.
 */

// URL parsing starts by decoding enough to catch path traversal attempts. Bad
// percent-encoding throws in decodeURIComponent, so invalid URLs are rejected
// instead of being normalized into something surprising.
function safelyDecode(rawValue: string): string | null {
  try {
    return decodeURIComponent(rawValue);
  } catch {
    return null;
  }
}

export class MediaRegistry {
  // This in-memory map is the only place that connects renderer-visible media
  // IDs to absolute filesystem paths. A folder scan replaces the whole map so
  // IDs from a previous folder stop resolving immediately.
  private readonly byId = new Map<string, string>();

  setItems(items: MediaFileRecord[]): void {
    this.byId.clear();
    for (const item of items) {
      this.byId.set(item.id, item.absolutePath);
    }
  }

  // Resolve a raw ID only if it looks like an ID, not a path. The IDs are hashes
  // generated by mediaScanner, so slashes, backslashes, and ".." are never valid.
  resolveId(id: string): string | null {
    if (!id || id.includes("/") || id.includes("\\") || id.includes("..")) return null;
    return this.byId.get(id) ?? null;
  }

  // pixvitta-media://media/<id> is the URL shape used by full-size images and
  // videos. After validating the protocol, host, and path, the method returns
  // the real file path for the current scan.
  resolveUrl(rawUrl: string): string | null {
    const decodedRawUrl = safelyDecode(rawUrl);
    if (!decodedRawUrl) return null;
    if (decodedRawUrl.includes("..") || decodedRawUrl.includes("\\")) return null;

    let url: URL;
    try {
      url = new URL(rawUrl);
    } catch {
      return null;
    }

    if (url.protocol !== "pixvitta-media:" || url.hostname !== "media") return null;
    const id = url.pathname.replace(/^\/+/, "");
    return this.resolveId(id);
  }

}
